### ISSUE TITLE
XLM-R with Abkhaz

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Caucasus-NLP-Data-Pipeline#107]
[Glot500](https://huggingface.co/cis-lmu/glot500-base) is a Roberta model that supports Abkhaz. Such a model can be used for various NLP tasks like machine translation as [EncoderDecoderModel](https://huggingface.co/docs/transformers/model_doc/encoder-decoder).

**Comment by danielinux7** [comment]
I just tried Glot500 on a simple mask for Abkhazian, it failed to give me an answer.

It seems Claude opus 3 has been trained on the Circassian langauage and gives good results, which is a sister language for Abkhazian, I don't know if Abkhazian is trained as well, because I don't have access to Claude in my region.

**Comment by danielinux7** [comment]
Abkhazian was included to Google Translate, the main goal is achieved, so I mclosing this issue.
